config/routes.rb
Sservice::Application.routes.draw do
  root :to => 'sservice#index', :as => 'home'
  match 'transact', :to => 'sservice#transact', :as => 'transact'
end

app/models/bundle.rb
class Bundle < ActiveRecord::Base
end

app/models/shopping.rb
class Shopping < ActiveRecord::Base
  has_one :bundle
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :list_shoppings

  def list_shoppings
    if session[:phonenumber] then
      @shoppings = Shopping.order('created_at DESC').where(['number = ?', session['phonenumber']])
    else
      @shoppings = []
    end
  end
end

app/controllers/sservice_controller.rb
class SserviceController < ApplicationController
  def index
    if request[:next] then
      session[:next] = request[:next]
    end
    @bundles = Bundle.order('amount')
    if session[:phonenumber] then
      @shoppings = Shopping.order('created_at DESC').where(['number = ?', session['phonenumber']])
    end
  end

  def transact
    if request[:phonenumber] then
      session[:phonenumber] = request[:phonenumber]
      if request[:bundle] then
        @bundle = Bundle.find_by_id request[:bundle]
        session[:bundle] = @bundle.id
        cpt = Sinapi::Account.new session[:phonenumber]
        ans = cpt.pay(:to => '256718202639', :amount => @bundle.amount, :currency => 'UGX', :test => :test, :comment => (%[%s: %s] % [@bundle.name, @bundle.descr]), :from => session[:phonenumber], :username => :scyfy, :password => :halpulaar)
        if ans.is_a? String then
          flash[:error] = ans
          redirect_to home_path
        else
          Shopping.create :bundle_id => @bundle.id, :number => session[:phonenumber]
          if session[:next] then
            session.delete :next
            redirect_to session[:next]
          else
            @balance = cpt.balance :username => :scyfy, :password => :halpulaar
          end
        end
      else
        flash[:error] = %[Choose a bundle.]
        redirect_to home_path
      end
    else
      flash[:error] = %[Enter a phone number.]
      redirect_to home_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sservice_helper.rb
module SserviceHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title ISP Self-Service
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    #main{:class => 'container'}
      #header{:class => 'span-24'}
        #logoface{:class => 'span-8'}
          ISP Self-Service
        #tagline{:class => 'span-16 last'}
          Internet credit top-up with mobile money.
      #trunk{:class => 'span-24'}
        #menulist{:class => 'span-4 prepend-4'}
          .littleheader One-Click Internet Credit Shopping
          Enter your phone number and PIN,
          choose the bundle you want to buy,
          and pay with your mobile money account.
          - if session[:phonenumber] then
            .littleheader
              Welcome back,
              = succeed '.' do
                %strong #{session[:phonenumber]}
            %table
              %thead
                %th Bundle
                %th When Bought
              %tbody
                - @shoppings.each do |shopping|
                  %tr
                    %td #{Bundle.find_by_id(shopping.bundle_id).name}
                    %td #{time_ago_in_words(shopping.created_at)} ago
        #tableau{:class => 'span-12 prepend-2 append-2 last'}
          = yield
      #footer{:class => 'span-24'}
        &copy; 2012,
        = succeed '.' do
          %a{:href => 'http://1st.ug/'} Scyfy Technologies
        All Rights Reserved.

app/views/sservice/index.html.haml
- if flash[:error] then
  .error
    = flash[:error]
= form_tag transact_path do
  %fieldset
    %legend Your Phone Number:
    = text_field_tag :phonenumber, session[:phonenumber], :class => 'numberer texter'
  %fieldset
    %legend Your PIN Code:
    = password_field_tag :pincode, session[:pincode], :class => :texter
  %fieldset
    %legend Pick Your Bundle:
    %table
      %thead
        %th Bundle
        %th Shs.
        %th
      %tbody
        - @bundles.each do |bundle|
          %tr
            %td{:class => 'bundlename'}
              %input{:type => 'radio', :name => :bundle, :id => (%[bundle_%d] % [bundle.id]), :value => bundle.id}
              %label{'for' => (%[bundle_%d] % [bundle.id])}#{bundle.name}
            %td{:class => 'bundlecost'} #{number_with_delimiter(bundle.amount)}
            %td{:class => 'bundledescr'} #{bundle.descr}
  = submit_tag 'Buy Internet Credit'

app/views/sservice/transact.html.haml
%table{:style => 'font-size: 200%; border: 1px solid #000; padding: 1em'}
  %thead
    %th Receipt Code
    %th #{Time.now.to_i.to_s(16)}
  %tbody
    %tr
      %td Bundle Name
      %td #{@bundle.name}
    %tr
      %td Bundle Description
      %td #{@bundle.descr}
    %tr
      %td Amount Paid
      %td UGX #{number_with_delimiter(@bundle.amount)}
    %tr
      %td Time
      %td #{Time.now.strftime('%H:%M %d %B, %Y')}
    %tr
      %td Paying Account
      %td #{session[:phonenumber]}
  %tfoot
    %td{:colspan => 2}
      %h2 Thank you.

%a{:href => 'javascript:window.print();'} Print Receipt
&bull;
%a{:href => '/'} Back Home